# Generated by Django 5.2.4 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('wk01', 'Week 1'), ('wk02', 'Week 2'), ('wk03', 'Week 3')], max_length=5, unique=True)),
                ('revenue', models.FloatField()),
                ('expense', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
